P= float(input("Enter the floatial principal balence: "))
R= float(input("enter the floaterest rate:  "))
N= float(input("enter the number of times floaterest applied per time period: "))
T= float(input("enter the number of time periods elapsed:  "))
U= float(R/N)
A=P*(1+U)**(U)
print("the compound floaterest anount is",A)
